#配置端口
server:
  port: 8088
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

#数据库配置
spring:
  datasource:
    url : jdbc:sqlserver://localhost:1433;DatabaseName=ACE_UAT
    username : sa
    password : P@ssw0rd
    driverClassName : com.microsoft.sqlserver.jdbc.SQLServerDriver


  devtools:
    add-properties: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: sql_server
    properties:


